language: java
jdk: oraclejdk8
branches:
  only: master
install: true
script: ".travis/build.sh"
after_success: ".travis/notify.sh Travis-Success"
after_failure: ".travis/notify.sh Travis-Failure"
env:
  global:
  - secure: KFmqEoqR96qHxtSyJ3HfiIZ1s+BBc/Xk9Vt/KOHtScPnO7hJ6SU5dFINrQh+rVTBgPCVFJOHOeOG9cz4oC9/gQBD6U3Gkkd6sI64/rWZzIST6x0RCzvKwbZ9vjVMklGOSQspRfVPPU/m9vAUo7aUfqHBF6CYYmwywFfh1L+kqOs=
  - secure: A6RhUT0vA7A/4h6ry6nXAvnukX+jnyA9ZqzIbE4ldNc9+Rhb2OxS5BhTKUtjNNa0fR2LkJvnqxbm/s5A2Og/H2kEolxMKtiRlQcHmbKrigQyryLEQ6v7HR6qWEPjBfAx341DGVeaZMWga4C0SXJPFX+QYHVXE0bCt2mWiI9QfIE=
